# Hexo Configuration

# Site
title: 皮蛋豆腐的博客
subtitle:
description:
author: jysperm
language: zh-CN
timezone: Asia/Shanghai
disqus_shortname: 'pidan-doufu'

# URL
url: http://pidan.cat
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  皮蛋: pidan
  豆腐: doufu

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 5
pagination_dir: page

# Extensions
theme: light

# Deployment
deploy:
  type: rsync
  host: ap-home.rpvhost.net
  user: www-data
  root: /home/www-data/cats-blog
